server:
  port: 8650
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
  application:
    name: demo
#  redis:
#    host: qadb-int.xiaozipu.cn
#    port: 6379
#    password: "PC8hXD76Vn3vJNye"
#    database: 1
#    timeout: 1800ms #连接超时时间
#    lettuce:
#      pool:
#        max-active: 8 #连接池最大连接数（使用负值表示没有限制） 默认 8
#        max-idle: 8 #连接池中的最大空闲连接 默认 8
#        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#        min-idle: 0 #连接池中的最小空闲连接 默认 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.224.62.94/hcloud_pf?useSSL=false
    username: root
    password: hh1024hh@
    #连接池配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 30
#        ######Druid监控配置######
#        web-stat-filter:
#          enabled: true
#          #哪些资源配置监控：主要只静态资源和监控地址本身
#          #exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
#        stat-view-servlet:
#          #IP 白名单
#          allow: 127.0.0.1
#          #IP 黑名单
#          #deny: 192.168.0.101
#          #监控地址,默认 /druid/*
#          url-pattern: /druid/*
#          login-username: jieshi
#          login-password: jieshii333
#  activemq:
#    broker-url: tcp://qa-int.xiaozipu.cn:8631
#    user: jscloud-pi
#    password: DSZ@^am@s9A7H7g
#    pool:
#      enabled: true
#      max-connections: 50
#      expiry-timeout: 10000
#      idle-timeout: 30000
#
##分页配置
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params:
#    count: countSql
#
##扫描映射文件
#mybatis:
#  mapper-locations: classpath*:mapper/**/*.xml
#mapper:
#  mappers: jscloud.common.base.mapper.BaseMapper
#  not-empty: false
#  identity: MYSQL
#
##swagger2配置信息
#swagger2:
#  enable: true
#  basePackage: jscloud.shop
#  title: API开发文档
#  desc:
#  termsOfServiceUrl: jscloud.shop
#  version: 1.0

logging:
  config: classpath:logback-spring.xml
  logback:
    level: DEBUG

#eureka:
#  client:
#    service-url:
#      defaultZone: http://qa-int.xiaozipu.cn:8610/eureka
#    instance:
#      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
#
#
#feign:
#  hystrix:
#    enabled: false
#  client:
#    config:
#      default:  # 服务名，default表示所有服务
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: full  # full | basic | none | headers
#
#tx-lcn:
#  client:
#    manager-address: 192.168.33.42:8626
