server:
  port: 8650
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
  application:
    name: demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.224.62.94/hcloud_pf?useSSL=false
    username: root
    password: hh1024hh@
    # ¡¨Ω”≥ÿ≈‰÷√
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 30

logging:
  config: classpath:logback-spring.xml
  logback:
    level: DEBUG
